[tools.task]
permission = "ask"
allowlist = [
    "explore",
]

[tools.bash]
allowlist = [
    "cd",
    "git add",
    "git branch",
    "git commit",
    "git config --global",
    "git config --list",
    "git log",
    "git push",
    "git remote -v",
    "git status",
    "grep",
]

[tools.write_file]
permission = "always"
